name: aucorsa_app
description: Aucorsa Bus Realtime App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # State Management (Cubit)
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7
  # Networking
  dio: ^5.7.0
  # Navigation
  go_router: ^17.0.0
  # Storage
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  # UI & Utils
  intl: any
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  # LEGACY (to be removed after migration)
  http: ^1.2.0
  provider: ^6.1.1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  flutter_riverpod: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/data/
